# Generated by Django 3.2.6 on 2021-08-28 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='recordlabel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rlp_records.recordlabel'),
        ),
        migrations.AlterField(
            model_name='record',
            name='audio_hash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='fingerprint',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rlp_records.erc721'),
        ),
    ]
