# Generated by Django 3.2.6 on 2021-09-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0002_auto_20210828_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=200, null=True)),
                ('fingerprint', models.BinaryField(null=True)),
                ('value', models.BinaryField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='audio_hash',
        ),
        migrations.RemoveField(
            model_name='record',
            name='fingerprint',
        ),
        migrations.AddField(
            model_name='record',
            name='audiofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rlp_records.audiofile'),
        ),
    ]
