# Generated by Django 3.2.6 on 2021-09-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0004_auto_20210914_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='value',
            new_name='file',
        ),
    ]
