# Generated by Django 3.2.6 on 2021-10-05 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0008_alter_erc721_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MINT', 'Mint')], max_length=100)),
                ('proof', models.CharField(max_length=200)),
                ('details', models.JSONField()),
                ('attributed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rlp_records.recordlabel')),
            ],
        ),
    ]
