# Generated by Django 3.2.6 on 2021-10-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0009_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erc721',
            old_name='metadataURI',
            new_name='metadata_uri',
        ),
        migrations.RenameField(
            model_name='erc721',
            old_name='tokenId',
            new_name='tokenid',
        ),
    ]
