# Generated by Django 3.2.6 on 2021-11-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0010_auto_20211006_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='sha256',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='hashstamp',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
