# Generated by Django 3.2.6 on 2021-12-19 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0013_rename_hashstamp_audiofile_fingerprinthash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rlp_records.record'),
        ),
    ]
