# Generated by Django 3.2.6 on 2022-09-14 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0014_alter_audiofile_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wallet_address',
            field=models.CharField(default=36769607454580604450338897478010123799187735419, max_length=42, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Wallet Address'),
            preserve_default=False,
        ),
    ]
