# Generated by Django 3.2.6 on 2022-09-14 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0015_member_walletaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='wallet_address',
            field=models.CharField(max_length=42, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
