# Generated by Django 3.2.6 on 2022-09-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rlp_records', '0016_alter_member_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attributed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rlp_records.record'),
        ),
    ]
