version: "3"
services:
  mongo:
    ports: 
      - "27017:27017"
    image: mongo
    volumes:
      - /var/tmp/rlprecordsdb:/data/db
      # TODO
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: rlprecords
    #   MONGO_INITDB_ROOT_PASSWORD: hunter2
