FROM python:3.8-alpine

RUN apk update -qq && apk upgrade

RUN apk add --no-cache build-base 

ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app/
COPY requirements.txt /usr/src/app/
RUN pip install -r requirements.txt
COPY . /usr/src/app/

